# include:
#  template: Dependency-Scanning.gitlab-ci.yml

stages:
  - test
  - release
  - docs

cache:
  paths:
    - node_modules/

unit:
  before_script:
    - yarn install --frozen-lockfile
  image: node:12
  stage: test
  script:
    - yarn test
  artifacts:
    paths:
    - node_modules/
    - coverage
    - report
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

tag:
  before_script:
    - yarn install --frozen-lockfile
  image: node:12
  stage: release
  script:
    - yarn release:tag
  artifacts:
    paths:
    - node_modules/
    - dist
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

publish:
  before_script:
    - yarn install --frozen-lockfile
  image: node:12
  stage: release
  script:
    - yarn release
  artifacts:
    paths:
    - node_modules/
  rules:
    - if: '$CI_COMMIT_TAG != null'

pages:
  before_script:
    - yarn install --frozen-lockfile
  image: node:12
  stage: docs
  script:
    - yarn styleguide:build
    - rm -rf ./public
    - mv styleguide public
  artifacts:
    paths:
    - node_modules/
    - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
